import type { Localized } from "@/lib/i18n";

/** Textos de interfaz. El contenido (proyectos, experiencia…) vive en los otros módulos. */
export const ui = {
  brand: {
    es: "Mi Portafolio",
    en: "My Portfolio",
    de: "Mein Portfolio",
    it: "Il mio portfolio",
    nl: "Mijn portfolio",
  },
  backToTop: {
    es: "Volver arriba",
    en: "Back to top",
    de: "Nach oben",
    it: "Torna su",
    nl: "Terug naar boven",
  },
  openMenu: {
    es: "Abrir menú",
    en: "Open menu",
    de: "Menü öffnen",
    it: "Apri menu",
    nl: "Menu openen",
  },
  closeMenu: {
    es: "Cerrar menú",
    en: "Close menu",
    de: "Menü schließen",
    it: "Chiudi menu",
    nl: "Menu sluiten",
  },
  switchLanguage: {
    es: "Cambiar idioma",
    en: "Switch language",
    de: "Sprache wechseln",
    it: "Cambia lingua",
    nl: "Taal wisselen",
  },
  moreLanguages: {
    es: "Más idiomas",
    en: "More languages",
    de: "Weitere Sprachen",
    it: "Altre lingue",
    nl: "Meer talen",
  },
  cv: {
    open: {
      es: "Ver CV",
      en: "View resume",
      de: "Lebenslauf ansehen",
      it: "Vedi CV",
      nl: "Cv bekijken",
    },
    title: {
      es: "Curriculum Vitae",
      en: "Resume",
      de: "Lebenslauf",
      it: "Curriculum Vitae",
      nl: "Curriculum vitae",
    },
    choose: {
      es: "Elige un idioma",
      en: "Choose a language",
      de: "Sprache auswählen",
      it: "Scegli una lingua",
      nl: "Kies een taal",
    },
    back: {
      es: "Volver a los idiomas",
      en: "Back to languages",
      de: "Zurück zu den Sprachen",
      it: "Torna alle lingue",
      nl: "Terug naar de talen",
    },
    download: {
      es: "Descargar PDF",
      en: "Download PDF",
      de: "PDF herunterladen",
      it: "Scarica PDF",
      nl: "PDF downloaden",
    },
    zoomIn: {
      es: "Acercar",
      en: "Zoom in",
      de: "Vergrößern",
      it: "Ingrandisci",
      nl: "Inzoomen",
    },
    zoomOut: {
      es: "Alejar",
      en: "Zoom out",
      de: "Verkleinern",
      it: "Riduci",
      nl: "Uitzoomen",
    },
    openTab: {
      es: "Abrir en pestaña nueva",
      en: "Open in new tab",
      de: "In neuem Tab öffnen",
      it: "Apri in una nuova scheda",
      nl: "In nieuw tabblad openen",
    },
    close: { es: "Cerrar", en: "Close", de: "Schließen", it: "Chiudi", nl: "Sluiten" },
  },
  theme: {
    group: { es: "Tema", en: "Theme", de: "Design", it: "Tema", nl: "Thema" },
    light: { es: "Claro", en: "Light", de: "Hell", it: "Chiaro", nl: "Licht" },
    system: { es: "Sistema", en: "System", de: "System", it: "Sistema", nl: "Systeem" },
    dark: { es: "Oscuro", en: "Dark", de: "Dunkel", it: "Scuro", nl: "Donker" },
  },

  nav: {
    home: { es: "Inicio", en: "Home", de: "Start", it: "Home", nl: "Start" },
    about: {
      es: "Sobre mí",
      en: "About",
      de: "Über mich",
      it: "Chi sono",
      nl: "Over mij",
    },
    experience: {
      es: "Experiencia",
      en: "Experience",
      de: "Erfahrung",
      it: "Esperienza",
      nl: "Ervaring",
    },
    projects: {
      es: "Proyectos",
      en: "Projects",
      de: "Projekte",
      it: "Progetti",
      nl: "Projecten",
    },
    skills: {
      es: "Habilidades",
      en: "Skills",
      de: "Fähigkeiten",
      it: "Competenze",
      nl: "Vaardigheden",
    },
    education: {
      es: "Educación",
      en: "Education",
      de: "Bildung",
      it: "Istruzione",
      nl: "Opleiding",
    },
    certifications: {
      es: "Certificaciones",
      en: "Certifications",
      de: "Zertifikate",
      it: "Certificazioni",
      nl: "Certificeringen",
    },
    contact: { es: "Contacto", en: "Contact", de: "Kontakt", it: "Contatti", nl: "Contact" },
  },

  hero: {
    viewProjects: {
      es: "Ver Proyectos",
      en: "View Projects",
      de: "Projekte ansehen",
      it: "Vedi progetti",
      nl: "Projecten bekijken",
    },
    stats: {
      projects: {
        es: "Proyectos",
        en: "Projects",
        de: "Projekte",
        it: "Progetti",
        nl: "Projecten",
      },
      technologies: {
        es: "Tecnologías",
        en: "Technologies",
        de: "Technologien",
        it: "Tecnologie",
        nl: "Technologieën",
      },
      certifications: {
        es: "Certificaciones",
        en: "Certifications",
        de: "Zertifikate",
        it: "Certificazioni",
        nl: "Certificeringen",
      },
      competitions: {
        es: "Competiciones",
        en: "Competitions",
        de: "Wettbewerbe",
        it: "Competizioni",
        nl: "Wedstrijden",
      },
    },
  },

  about: {
    title: {
      es: "Sobre mí",
      en: "About Me",
      de: "Über mich",
      it: "Chi sono",
      nl: "Over mij",
    },
  },

  experience: {
    title: {
      es: "Experiencia",
      en: "Experience",
      de: "Erfahrung",
      it: "Esperienza",
      nl: "Ervaring",
    },
    seeMore: {
      es: "Ver más sobre el puesto",
      en: "See more about this role",
      de: "Mehr über diese Stelle",
      it: "Scopri di più sul ruolo",
      nl: "Meer over deze functie",
    },
    seeLess: {
      es: "Ver menos",
      en: "See less",
      de: "Weniger anzeigen",
      it: "Mostra meno",
      nl: "Minder tonen",
    },
    present: { es: "Presente", en: "Present", de: "Heute", it: "Presente", nl: "Heden" },
  },

  projects: {
    title: {
      es: "Proyectos Destacados",
      en: "Featured Projects",
      de: "Ausgewählte Projekte",
      it: "Progetti in evidenza",
      nl: "Uitgelichte projecten",
    },
    viewProject: {
      es: "Ver Proyecto",
      en: "View Project",
      de: "Projekt ansehen",
      it: "Vedi progetto",
      nl: "Project bekijken",
    },
    viewCode: {
      es: "Ver Código",
      en: "View Code",
      de: "Code ansehen",
      it: "Vedi codice",
      nl: "Code bekijken",
    },
    demo: { es: "Demo", en: "Demo", de: "Demo", it: "Demo", nl: "Demo" },
    website: {
      es: "Sitio Web",
      en: "Website",
      de: "Webseite",
      it: "Sito web",
      nl: "Website",
    },
    privateProject: {
      es: "Proyecto privado de cliente",
      en: "Private client project",
      de: "Privates Kundenprojekt",
      it: "Progetto privato di un cliente",
      nl: "Privéproject van een klant",
    },
    collaborator: {
      es: "Colaborador",
      en: "Collaborator",
      de: "Mitwirkender",
      it: "Collaboratore",
      nl: "Medewerker",
    },
    empty: {
      es: "No hay proyectos en esta categoría.",
      en: "No projects in this category.",
      de: "Keine Projekte in dieser Kategorie.",
      it: "Nessun progetto in questa categoria.",
      nl: "Geen projecten in deze categorie.",
    },
    filters: {
      all: { es: "Todos", en: "All", de: "Alle", it: "Tutti", nl: "Alle" },
      development: {
        es: "Desarrollo",
        en: "Development",
        de: "Entwicklung",
        it: "Sviluppo",
        nl: "Ontwikkeling",
      },
      ai: {
        es: "IA & Machine Learning",
        en: "AI & Machine Learning",
        de: "KI & Machine Learning",
        it: "IA & Machine Learning",
        nl: "AI & Machine Learning",
      },
      security: {
        es: "Ciberseguridad",
        en: "Cybersecurity",
        de: "Cybersicherheit",
        it: "Cybersicurezza",
        nl: "Cybersecurity",
      },
      systems: { es: "Sistemas", en: "Systems", de: "Systeme", it: "Sistemi", nl: "Systemen" },
      data: { es: "Datos", en: "Data", de: "Daten", it: "Dati", nl: "Data" },
      collab: {
        es: "Colaboraciones",
        en: "Collaborations",
        de: "Kollaborationen",
        it: "Collaborazioni",
        nl: "Samenwerkingen",
      },
    },
  },

  skills: {
    title: {
      es: "Habilidades",
      en: "Skills",
      de: "Fähigkeiten",
      it: "Competenze",
      nl: "Vaardigheden",
    },
    viewInSkills: {
      es: "Ver en Habilidades",
      en: "See in Skills",
      de: "In Fähigkeiten ansehen",
      it: "Vedi nelle competenze",
      nl: "Bekijk bij vaardigheden",
    },
  },

  education: {
    title: {
      es: "Educación & Competiciones",
      en: "Education & Competitions",
      de: "Bildung & Wettbewerbe",
      it: "Istruzione & Competizioni",
      nl: "Opleiding & Wedstrijden",
    },
    competitions: {
      es: "Competiciones",
      en: "Competitions",
      de: "Wettbewerbe",
      it: "Competizioni",
      nl: "Wedstrijden",
    },
    currentCourses: {
      es: "Ramos destacados este semestre",
      en: "Highlighted courses this semester",
      de: "Ausgewählte Kurse in diesem Semester",
      it: "Corsi in evidenza di questo semestre",
      nl: "Uitgelichte vakken dit semester",
    },
    rankings: {
      team: {
        es: "Ranking por equipos",
        en: "Team ranking",
        de: "Teamwertung",
        it: "Classifica a squadre",
        nl: "Teamklassement",
      },
      individual: {
        es: "Ranking individual",
        en: "Individual ranking",
        de: "Einzelwertung",
        it: "Classifica individuale",
        nl: "Individueel klassement",
      },
      world: {
        es: "Ranking mundial",
        en: "Worldwide ranking",
        de: "Weltrangliste",
        it: "Classifica mondiale",
        nl: "Wereldranglijst",
      },
    },
    of: { es: "de", en: "of", de: "von", it: "su", nl: "van" },
    leader: { es: "líder", en: "leader", de: "Spitze", it: "leader", nl: "koploper" },
    points: { es: "pts", en: "pts", de: "Pkt.", it: "pt", nl: "ptn" },
    contribution: {
      es: "del puntaje del equipo",
      en: "of the team score",
      de: "der Teampunktzahl",
      it: "del punteggio della squadra",
      nl: "van de teamscore",
    },
    categories: {
      es: "Categorías",
      en: "Categories",
      de: "Kategorien",
      it: "Categorie",
      nl: "Categorieën",
    },
    comingSoon: {
      es: "Próximamente",
      en: "Coming soon",
      de: "Demnächst",
      it: "Prossimamente",
      nl: "Binnenkort",
    },
    comingSoonTitle: {
      es: "Se vienen más competencias",
      en: "More competitions on the way",
      de: "Weitere Wettbewerbe folgen",
      it: "Altre competizioni in arrivo",
      nl: "Er komen meer wedstrijden aan",
    },
    comingSoonText: {
      es: "Nuevos CTF y hackathons en camino. Esta sección se sigue actualizando.",
      en: "New CTFs and hackathons on the way. This section keeps growing.",
      de: "Neue CTFs und Hackathons sind geplant. Dieser Bereich wird laufend ergänzt.",
      it: "Nuovi CTF e hackathon in arrivo. Questa sezione continua a crescere.",
      nl: "Nieuwe CTF's en hackathons op komst. Dit onderdeel wordt steeds aangevuld.",
    },
    readNews: {
      es: "Ver noticia",
      en: "Read article",
      de: "Artikel lesen",
      it: "Leggi la notizia",
      nl: "Lees het artikel",
    },
  },

  certifications: {
    title: {
      es: "Certificaciones",
      en: "Certifications",
      de: "Zertifikate",
      it: "Certificazioni",
      nl: "Certificeringen",
    },
    completed: {
      es: "Completado",
      en: "Completed",
      de: "Abgeschlossen",
      it: "Completato",
      nl: "Afgerond",
    },
    inProgress: {
      es: "En Progreso",
      en: "In Progress",
      de: "In Arbeit",
      it: "In corso",
      nl: "Bezig",
    },
    completedCount: {
      es: "completadas",
      en: "completed",
      de: "abgeschlossen",
      it: "completate",
      nl: "afgerond",
    },
    viewCredentials: {
      es: "Ver Credenciales",
      en: "View Credentials",
      de: "Nachweise ansehen",
      it: "Vedi credenziali",
      nl: "Certificaten bekijken",
    },
    close: { es: "Cerrar", en: "Close", de: "Schließen", it: "Chiudi", nl: "Sluiten" },
    back: { es: "Volver", en: "Back", de: "Zurück", it: "Indietro", nl: "Terug" },
    labIntro: {
      es: "Exam Lab práctico: se aprueba resolviendo tareas en vivo sobre infraestructura real de AWS, no con preguntas de opción múltiple.",
      en: "Hands-on Exam Lab: passed by completing live tasks on real AWS infrastructure, not by answering multiple-choice questions.",
      de: "Praktisches Exam Lab: Bestanden wird durch Live-Aufgaben auf echter AWS-Infrastruktur, nicht durch Multiple-Choice-Fragen.",
      it: "Exam Lab pratico: si supera svolgendo attività dal vivo su infrastruttura AWS reale, non con domande a risposta multipla.",
      nl: "Praktisch Exam Lab: je slaagt door live taken uit te voeren op echte AWS-infrastructuur, niet met meerkeuzevragen.",
    },
    labTasks: {
      es: "Lo que se implementa",
      en: "What gets implemented",
      de: "Was umgesetzt wird",
      it: "Cosa si implementa",
      nl: "Wat er wordt geïmplementeerd",
    },
    verify: {
      es: "Verificar",
      en: "Verify",
      de: "Überprüfen",
      it: "Verifica",
      nl: "Verifiëren",
    },
    verifyPending: {
      es: "Verificable al completarla",
      en: "Verifiable once completed",
      de: "Nach Abschluss überprüfbar",
      it: "Verificabile una volta completata",
      nl: "Verifieerbaar na afronding",
    },
    code: { es: "Código", en: "Code", de: "Code", it: "Codice", nl: "Code" },
    copyCode: {
      es: "Clic para copiar",
      en: "Click to copy",
      de: "Zum Kopieren klicken",
      it: "Clicca per copiare",
      nl: "Klik om te kopiëren",
    },
    copied: {
      es: "¡Copiado!",
      en: "Copied!",
      de: "Kopiert!",
      it: "Copiato!",
      nl: "Gekopieerd!",
    },
    groups: {
      securityNetworking: {
        es: "Ciberseguridad y Redes",
        en: "Cybersecurity & Networking",
        de: "Cybersicherheit & Netzwerke",
        it: "Cybersicurezza e Reti",
        nl: "Cybersecurity en Netwerken",
      },
      languages: {
        es: "Idiomas",
        en: "Languages",
        de: "Sprachen",
        it: "Lingue",
        nl: "Talen",
      },
      cloud: { es: "Cloud", en: "Cloud", de: "Cloud", it: "Cloud", nl: "Cloud" },
    },
  },

  contact: {
    title: { es: "Contacto", en: "Contact", de: "Kontakt", it: "Contatti", nl: "Contact" },
    description: {
      es: "¿Interesado en colaborar o tienes alguna pregunta? ¡No dudes en contactarme!",
      en: "Interested in collaborating or have any questions? Feel free to reach out!",
      de: "Interesse an einer Zusammenarbeit oder Fragen? Melde dich einfach!",
      it: "Ti interessa collaborare o hai qualche domanda? Scrivimi pure!",
      nl: "Interesse in samenwerken of heb je een vraag? Neem gerust contact op!",
    },
    emailMe: {
      es: "Escríbeme",
      en: "Email me",
      de: "Schreib mir",
      it: "Scrivimi",
      nl: "Mail me",
    },
    email: { es: "Correo", en: "Email", de: "E-Mail", it: "Email", nl: "E-mail" },
    location: {
      es: "Ubicación",
      en: "Location",
      de: "Standort",
      it: "Posizione",
      nl: "Locatie",
    },
    copyEmail: {
      es: "Copiar correo",
      en: "Copy email",
      de: "E-Mail kopieren",
      it: "Copia l'email",
      nl: "E-mail kopiëren",
    },
    copied: {
      es: "¡Copiado!",
      en: "Copied!",
      de: "Kopiert!",
      it: "Copiato!",
      nl: "Gekopieerd!",
    },
  },

  footer: {
    rights: {
      es: "© 2026 Maximiliano Solorza. Todos los derechos reservados.",
      en: "© 2026 Maximiliano Solorza. All rights reserved.",
      de: "© 2026 Maximiliano Solorza. Alle Rechte vorbehalten.",
      it: "© 2026 Maximiliano Solorza. Tutti i diritti riservati.",
      nl: "© 2026 Maximiliano Solorza. Alle rechten voorbehouden.",
    },
    builtWith: {
      es: "Hecho con Next.js, Tailwind CSS y Motion.",
      en: "Built with Next.js, Tailwind CSS and Motion.",
      de: "Gebaut mit Next.js, Tailwind CSS und Motion.",
      it: "Realizzato con Next.js, Tailwind CSS e Motion.",
      nl: "Gemaakt met Next.js, Tailwind CSS en Motion.",
    },
  },
} satisfies Record<string, unknown>;

/** Orden de las secciones en la barra y en la página. */
export const SECTION_IDS = [
  "home",
  "about",
  "experience",
  "projects",
  "skills",
  "education",
  "certifications",
  "contact",
] as const satisfies readonly (keyof typeof ui.nav)[];

export type SectionId = (typeof SECTION_IDS)[number];

export type UiText = Localized;
